DROP DATABASE EMPLOYEES; 

CREATE DATABASE EMPLOYEES; 


USE EMPLOYEES; 


CREATE TABLE COMPANY ( 
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
   COMPANYNAME VARCHAR(30) 
); 


CREATE TABLE EMPLOYEE ( 
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
   FIRSTNAME VARCHAR(10), 
   LASTNAME VARCHAR(20), 
   BIRTHDAY DATE, 
   GENDER VARCHAR(6), 
   COMPANY INT, 
   HIREDATE TIMESTAMP, 
   SALARY DOUBLE, 
   CHILDREN INT, 
   FOREIGN KEY(COMPANY) REFERENCES COMPANY(ID) 
); 


CREATE TABLE DEPARTMENT ( 
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
   DEPARTMENTNAME VARCHAR(20) 
); 


CREATE TABLE ASSIGNMENT ( 
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
   EMPLOYEE INT, 
   DEPARTMENT INT, 
   FOREIGN KEY(EMPLOYEE) REFERENCES EMPLOYEE(ID), 
   FOREIGN KEY(DEPARTMENT) REFERENCES DEPARTMENT(ID) 
); 

COMMIT;