#ifndef QUBICONS_GLOBAL_H
#define QUBICONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QUBICONS_LIBRARY)
#  define QUBICONSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QUBICONSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QUBICONS_GLOBAL_H
